FROM debian:jessie

ENV DEBIAN_FRONTEND noninteractive
ADD debian-patch/etc /etc

# install_tools
RUN apt-get --quiet --quiet update && apt-get --assume-yes upgrade

RUN apt-get --quiet --quiet install curl vim-nox
COPY vim-patch/vimrc.tgz /root/
RUN cd /root && tar xzf /root/vimrc.tgz && rm /root/vimrc.tgz

RUN curl https://repo.saltstack.com/apt/debian/8/amd64/latest/SALTSTACK-GPG-KEY.pub | apt-key add -

RUN echo 'deb http://repo.saltstack.com/apt/debian/8/amd64/latest jessie main' > /etc/apt/sources.list.d/salt.list

RUN apt-get --quiet --quiet update && apt-get --assume-yes upgrade
RUN apt-get --quiet --quiet install salt-master salt-minion python-redis

ADD salt-patch/etc /etc

RUN mkdir -p /var/cache/salt /var/cache/salt/master /var/cache/salt/master/jobs /var/run/salt /var/run/salt/master && chmod 755 /var/cache/salt /var/cache/salt/master /var/cache/salt/master/jobs /var/run/salt /var/run/salt/master

EXPOSE 4505 4506

CMD /usr/bin/salt-minion -d && /usr/bin/salt-master --log-level=info
